[package]
name = "lib_chat_gpt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
dotenv = "0.15.0"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1.38.0", features = ["full"] }
